/* Run against a local preview: PLAYWRIGHT_MODULE=/path/to/playwright node dev/experience-browser.cjs */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const base=process.env.EM_PREVIEW_URL||'http://127.0.0.1:8876/';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{for(const width of (process.env.EM_WIDTHS||"1280,390,320").split(",").map(Number)){
const context=await browser.newContext({viewport:{width,height:900},isMobile:width<700,hasTouch:width<700,reducedMotion:'reduce',acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>document.getElementById('disclaimerOverlay')?.remove(),{once:true}));
await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForSelector('.workspace-entry');assert.equal(await page.locator('.workspace-entry>a').count(),3);
const route=async target=>{await page.evaluate(target=>new Promise(resolve=>{if(location.hash==='#'+target)return resolve();addEventListener('hashchange',()=>requestAnimationFrame(()=>resolve()),{once:true});location.hash=target;}),target);};
const check=async()=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Overflow at '+width+' '+page.url());};
await check();const data=await page.evaluate(()=>({cases:EM_LEARNING_DATA.cases,modules:EM_LEARNING_DATA.modules,visuals:EM_LEARNING.visuals}));
for(const c of data.cases){for(const choice of ['b','a']){await route('learn~case-'+c.id);if(await page.locator('[data-case-retry]').count())await page.locator('[data-case-retry]').click();for(let i=0;i<c.steps.length;i++){assert.equal(await page.locator('[data-case-next]').count(),0);assert.ok(!(await page.locator('.workspace-body').innerText()).includes(c.steps[i].options[0].why));await page.locator('[data-evolving-choice='+choice+']').click();assert.ok((await page.locator('.workspace-feedback').innerText()).includes(c.steps[i].options.find(o=>o.id===choice).why));if(c.id==='resus'&&i===0&&choice==='b'){await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-case-next]');await route('learn~progress');await route('learn~case-resus');assert.equal(await page.locator('[data-case-next]').count(),1);}await check();await page.locator('[data-case-next]').click();}assert.equal(await page.locator('.workspace-result').count(),1);assert.match(await page.locator('.workspace-result').innerText(),choice==='a'?/3 \/ 3 first choices/:/0 \/ 3 first choices/);}}
console.log(width+': all 6 cases, correct/incorrect choices, sequential disclosure and resume passed');
for(const m of data.modules){await route('learn~module-'+m.id);assert.equal(await page.locator('[data-module-read]').count(),1);await page.locator('.workspace-callout summary').click();await page.locator('[data-readiness]').first().check();assert.match(await page.locator('[data-readiness-status]').innerText(),/1 \/ 3/);await page.locator('[data-module-read]').click();await check();}
for(const [id]of data.visuals){await route('learn~visual-'+id);await check();if(id==='ecg-pairs'){for(const value of ['wellens-a,wellens-b','normal,af','inferior-stemi,anterior-stemi']){await page.locator('#ecgPair').selectOption(value);assert.equal(await page.locator('.workspace-ecg svg').count(),2);await check();}}else if(id==='recordings'){for(const record of ['0','1','2','3']){await page.locator('[data-recording]').selectOption(record);for(const lead of ['0','1','6','11']){await page.locator('[data-recording-lead]').selectOption(lead);await page.locator('[data-recording-time]').selectOption('6');assert.equal(await page.locator('.recording-scroll svg').count(),1);await check();}}await page.locator('[data-recording-answer] summary').click();}else await page.locator('.workspace-callout summary').click();await page.locator('[data-module-read]').click();}
await route('learn~practice');await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:'/tmp/em-complete-practice-'+width+'.png',fullPage:true});
await page.evaluate(()=>document.documentElement.dataset.theme='dark');await route('learn~visual-abg');await page.locator('.workspace-callout summary').click();await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:'/tmp/em-complete-visual-'+width+'.png',fullPage:true});await check();
await page.locator('#searchInput').fill('SBAR');await page.waitForSelector('.res-item[data-id="learn"]');await page.locator('.res-item[data-id="learn"]').first().click();await page.waitForSelector('[data-module-read="handover"]');
await route('chest-pain');assert.equal(await page.locator('#section-study .guided-reasoning').count(),1);assert.equal(await page.locator('.reassessment-guide').count(),1);await page.locator('input[data-rf]').first().check();assert.match(await page.locator('#rfBanner').innerText(),/not a severity score/);
await route('learn~progress');assert.ok((await page.locator('.workspace-body').innerText()).includes('6 / 6 evolving cases attempted'));
await page.evaluate(()=>localStorage.setItem('em-cps-learning',JSON.stringify({reviewed:{},reviewPlan:{},saved:{},notes:{'chest-pain':'Keep this synthetic note'}})));
const downloaded=page.waitForEvent('download');await page.locator('[data-backup-export]').click();const download=await downloaded;assert.ok(download.suggestedFilename().endsWith('.json'));
const values={'em-cps-learning':{reviewed:{},reviewPlan:{},saved:{},notes:{'chest-pain':'Do not overwrite',shock:'Imported synthetic note'}}};await page.locator('[data-backup-file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'EM Pocket free',version:1,values}))});await page.waitForSelector('[data-backup-apply]');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('em-cps-learning')).notes.shock),undefined);await page.locator('[data-backup-apply]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('em-cps-learning')).notes['chest-pain']),'Keep this synthetic note');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('em-cps-learning')).notes.shock),'Imported synthetic note');
await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration())?.active);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);for(const path of ['learn~practice','learn~visual-lung','learn~visual-recordings','learn~module-handover','learn~progress','ecg-explorer~normal']){await page.goto(base+'#'+path,{waitUntil:'domcontentloaded'});await page.waitForSelector(path.startsWith('learn')?'.learning-workspace':'.explorer-findings');await check();}await context.setOffline(false);
await route('learn~module-handover');await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('blocked')}});await page.locator('[data-module-read]').click();assert.match(await page.locator('.module-save').innerText(),/session/);await route('learn~progress');assert.ok((await page.locator('.workspace-body').innerText()).includes('modules marked read'));assert.deepEqual(errors,[]);console.log(width+': modules, visuals, search, backup preview/merge, offline and storage-failure checks passed');await context.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
